# Generated by Django 5.0.6 on 2024-06-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('initial_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photos', models.JSONField()),
                ('color', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
