# Generated by Django 4.1.13 on 2024-06-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('initial_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pic', models.ImageField(default='best_selling_product_images/default_image.jpg', upload_to='best_selling_product_images/')),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Coral', 'Coral'), ('Space Gray', 'Space Gray'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Rose Gold', 'Rose Gold'), ('Midnight', 'Midnight'), ('Starlight', 'Starlight'), ('Jet Black', 'Jet Black'), ('Graphite', 'Graphite'), ('Pacific Blue', 'Pacific Blue'), ('Midnight Green', 'Midnight Green'), ('Sierra Blue', 'Sierra Blue'), ('Alpine Green', 'Alpine Green'), ('Deep Purple', 'Deep Purple'), ('Slate', 'Slate')], default='Red', max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.IntegerField(null=True)),
                ('category', models.CharField(blank=True, choices=[('NewiPhone', 'New iPhone'), ('OldiPhone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android')], max_length=500, null=True)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promodis', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('initial_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('pic', models.ImageField(default='feature_product_images/default_image.jpg', upload_to='feature_product_images/')),
                ('sale_end_time', models.DateTimeField()),
                ('category', models.CharField(blank=True, choices=[('NewiPhone', 'New iPhone'), ('OldiPhone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android')], max_length=500, null=True)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.IntegerField(null=True)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Coral', 'Coral'), ('Space Gray', 'Space Gray'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Rose Gold', 'Rose Gold'), ('Midnight', 'Midnight'), ('Starlight', 'Starlight'), ('Jet Black', 'Jet Black'), ('Graphite', 'Graphite'), ('Pacific Blue', 'Pacific Blue'), ('Midnight Green', 'Midnight Green'), ('Sierra Blue', 'Sierra Blue'), ('Alpine Green', 'Alpine Green'), ('Deep Purple', 'Deep Purple'), ('Slate', 'Slate')], default='Red', max_length=50)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('initial_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pic', models.ImageField(default='flash_sale_photos/default_photo.jpg', upload_to='flash_sale_photos/')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Pay with Cash'), ('delivery', 'Pay with Delivery')], max_length=10)),
                ('products', models.JSONField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('initial_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pic', models.ImageField(default='path/to/default/image.jpg', upload_to='product_images/')),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Coral', 'Coral'), ('Space Gray', 'Space Gray'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Rose Gold', 'Rose Gold'), ('Midnight', 'Midnight'), ('Starlight', 'Starlight'), ('Jet Black', 'Jet Black'), ('Graphite', 'Graphite'), ('Pacific Blue', 'Pacific Blue'), ('Midnight Green', 'Midnight Green'), ('Sierra Blue', 'Sierra Blue'), ('Alpine Green', 'Alpine Green'), ('Deep Purple', 'Deep Purple'), ('Slate', 'Slate')], default='Red', max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.IntegerField(null=True)),
                ('category', models.CharField(blank=True, choices=[('NewiPhone', 'New iPhone'), ('OldiPhone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android')], max_length=500, null=True)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
