# Generated by Django 5.0.6 on 2024-06-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('feature_image', models.ImageField(default='feature_product_images/default_image.jpg', upload_to='feature_product_images/')),
                ('sale_end_time', models.DateTimeField()),
                ('Category', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='feature_product_images/'),
        ),
    ]
