# Generated by Django 4.1.13 on 2024-06-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellingproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('NewiPhone', 'New iPhone'), ('OldiPhone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android'), ('Accessories', 'Accessories')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='featureproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('NewiPhone', 'New iPhone'), ('OldiPhone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android'), ('Accessories', 'Accessories')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('NewiPhone', 'New iPhone'), ('OldiPhone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android'), ('Accessories', 'Accessories')], max_length=500, null=True),
        ),
    ]
