# Generated by Django 5.0.6 on 2024-06-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_featureproduct_remove_product_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='feature_image',
        ),
        migrations.AddField(
            model_name='featureproduct',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featureproduct',
            name='color',
            field=models.CharField(default='default_color', max_length=50),
        ),
        migrations.AddField(
            model_name='featureproduct',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='default_color', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
