# Generated by Django 4.1.13 on 2024-06-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_product_available_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.ImageField(default='order_photos/default_photo.jpg', upload_to='order_photos/'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('NewiPhone', 'New iPhone'), ('OldiPhone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android'), ('Accessories', 'Accessories')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Coral', 'Coral'), ('Space Gray', 'Space Gray'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Rose Gold', 'Rose Gold'), ('Midnight', 'Midnight'), ('Starlight', 'Starlight'), ('Jet Black', 'Jet Black'), ('Graphite', 'Graphite'), ('Pacific Blue', 'Pacific Blue'), ('Midnight Green', 'Midnight Green'), ('Sierra Blue', 'Sierra Blue'), ('Alpine Green', 'Alpine Green'), ('Deep Purple', 'Deep Purple'), ('Slate', 'Slate')], default='Red', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='final_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='initial_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='product_images/'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default=12),
            preserve_default=False,
        ),
    ]
