# Generated by Django 5.0.6 on 2024-06-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_product_feature_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureproduct',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
    ]
