# Generated by Django 5.0.6 on 2024-06-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_featureproduct_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureproduct',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='featureproduct',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
