# Generated by Django 4.1.13 on 2024-06-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_photo_order_title_product_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=10),
        ),
    ]
