# Generated by Django 4.1.13 on 2024-06-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_order_photo_remove_order_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enhance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='enhance/default_photo.jpg', upload_to='enhance/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
