# Generated by Django 4.1.13 on 2024-06-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='picture',
        ),
    ]
