# Generated by Django 4.1.13 on 2024-06-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellingproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
