# Generated by Django 4.1.13 on 2024-06-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_bestsellingproduct_warrenty_featureproduct_warrenty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellingproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('Newiphone', 'New iPhone'), ('OldIphone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='featureproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('Newiphone', 'New iPhone'), ('OldIphone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Newiphone', 'New iPhone'), ('OldIphone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android')], max_length=500, null=True),
        ),
    ]
