# Generated by Django 4.1.13 on 2024-06-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_bestsellingproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellingproduct',
            name='warrenty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='featureproduct',
            name='warrenty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='warrenty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warrenty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
