# Generated by Django 4.1.13 on 2024-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_bestsellingproduct_warrenty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestsellingproduct',
            name='Storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='featureproduct',
            name='Storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='Storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='Storage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
