# Generated by Django 4.1.13 on 2024-06-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_bestsellingproduct_storage_featureproduct_storage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestsellingproduct',
            old_name='Storage',
            new_name='storage',
        ),
        migrations.RenameField(
            model_name='featureproduct',
            old_name='Storage',
            new_name='storage',
        ),
        migrations.RenameField(
            model_name='flashsale',
            old_name='Storage',
            new_name='storage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Storage',
            new_name='storage',
        ),
        migrations.AlterField(
            model_name='bestsellingproduct',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple')], default='Red', max_length=50),
        ),
        migrations.AlterField(
            model_name='featureproduct',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple')], default='Red', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple')], default='Red', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
