# Generated by Django 4.1.13 on 2024-06-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_product_thumbnail1_product_thumbnail2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail3',
        ),
    ]
