# Generated by Django 4.1.13 on 2024-06-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_product_thumbnail1_remove_product_thumbnail2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestsellingproduct',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='featureproduct',
            old_name='final_price',
            new_name='final_rate',
        ),
        migrations.RenameField(
            model_name='featureproduct',
            old_name='initial_price',
            new_name='initial_rate',
        ),
        migrations.RenameField(
            model_name='featureproduct',
            old_name='feature_image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='featureproduct',
            old_name='warrenty',
            new_name='warranty',
        ),
        migrations.RenameField(
            model_name='flashsale',
            old_name='final_price',
            new_name='final_rate',
        ),
        migrations.RenameField(
            model_name='flashsale',
            old_name='initial_price',
            new_name='initial_rate',
        ),
        migrations.RenameField(
            model_name='flashsale',
            old_name='warrenty',
            new_name='warranty',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='warrenty',
            new_name='warranty',
        ),
        migrations.RemoveField(
            model_name='bestsellingproduct',
            name='warrenty',
        ),
        migrations.AddField(
            model_name='bestsellingproduct',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
