# Generated by Django 4.1.13 on 2024-06-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_image_bestsellingproduct_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashsale',
            old_name='discount_percentage',
            new_name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='product_id',
        ),
    ]
