# Generated by Django 4.1.13 on 2024-06-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_discount_percentage_flashsale_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellingproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('NewiPhone', 'New iPhone'), ('OldiPhone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bestsellingproduct',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Coral', 'Coral'), ('Space Gray', 'Space Gray'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Rose Gold', 'Rose Gold'), ('Midnight', 'Midnight'), ('Starlight', 'Starlight'), ('Jet Black', 'Jet Black'), ('Graphite', 'Graphite'), ('Pacific Blue', 'Pacific Blue'), ('Midnight Green', 'Midnight Green'), ('Sierra Blue', 'Sierra Blue'), ('Alpine Green', 'Alpine Green'), ('Deep Purple', 'Deep Purple'), ('Slate', 'Slate')], default='Red', max_length=50),
        ),
        migrations.AlterField(
            model_name='featureproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('NewiPhone', 'New iPhone'), ('OldiPhone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='featureproduct',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Coral', 'Coral'), ('Space Gray', 'Space Gray'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Rose Gold', 'Rose Gold'), ('Midnight', 'Midnight'), ('Starlight', 'Starlight'), ('Jet Black', 'Jet Black'), ('Graphite', 'Graphite'), ('Pacific Blue', 'Pacific Blue'), ('Midnight Green', 'Midnight Green'), ('Sierra Blue', 'Sierra Blue'), ('Alpine Green', 'Alpine Green'), ('Deep Purple', 'Deep Purple'), ('Slate', 'Slate')], default='Red', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('NewiPhone', 'New iPhone'), ('OldiPhone', 'Old iPhone'), ('Cover', 'Cover'), ('Electronics', 'Electronics'), ('NewAndroid', 'New Android'), ('UsedAndroid', 'Used Android'), ('Laptop', 'Laptop'), ('Earbuds', 'Earbuds'), ('Android', 'Android')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('White', 'White'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Coral', 'Coral'), ('Space Gray', 'Space Gray'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Rose Gold', 'Rose Gold'), ('Midnight', 'Midnight'), ('Starlight', 'Starlight'), ('Jet Black', 'Jet Black'), ('Graphite', 'Graphite'), ('Pacific Blue', 'Pacific Blue'), ('Midnight Green', 'Midnight Green'), ('Sierra Blue', 'Sierra Blue'), ('Alpine Green', 'Alpine Green'), ('Deep Purple', 'Deep Purple'), ('Slate', 'Slate')], default='Red', max_length=50),
        ),
    ]
