# Generated by Django 4.1.13 on 2024-06-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_bestsellingproduct_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promodis', models.CharField(max_length=255)),
            ],
        ),
    ]
