# Generated by Django 4.1.13 on 2024-06-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestsellingproduct',
            old_name='photo',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='flashsale',
            old_name='photo',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='pic',
        ),
        migrations.RemoveField(
            model_name='featureproduct',
            name='photo',
        ),
        migrations.AddField(
            model_name='featureproduct',
            name='pic',
            field=models.ImageField(default='feature_product_images/default_image.jpg', upload_to='feature_product_images/'),
        ),
    ]
