# Generated by Django 4.1.13 on 2024-06-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_timerecord_remove_flashsale_discount_percent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeRecord',
        ),
        migrations.AddField(
            model_name='flashsale',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
