# Generated by Django 4.1.13 on 2024-06-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_timerecord_remove_flashsale_days_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeRecord',
        ),
        migrations.AddField(
            model_name='flashsale',
            name='remaining_time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
